// react/src/components/ImplSwitcher/ImplSwitcher.tsx
import React, { useState } from "react";
import cx from "classnames";
import './ImplSwitcher.scss';

export function ImplSwitcher() {
  const [hidden, setHidden] = useState(false);

  const toggleHidden = () => {
    setHidden((v) => !v);
  };

  return (
    <div
      className={cx(
        "fixed shadow-md bottom-4 right-4 flex gap-4 p-4 bg-emerald-600 rounded-md text-white transition-transform",
        hidden ? "translate-x-[85%]" : ''
      )}
    >
      <div className="flex flex-col justify-between">
        <i className="text-5xl fa-brands fa-angular"></i>
        <button
          onClick={() => toggleHidden()}
          className="text-md text-emerald-400"
        >
          <i className={cx('fa-solid', hidden ? 'fa-arrow-left' : 'fa-arrow-right')}></i>
        </button>
      </div>
      <div className="flex flex-col items-start justify-between">
        <span className="text-emerald-200">
          This site was built with React.
        </span>
        <span className="text-emerald-200">Need an Angular developer?</span>
        <a href="/">
          <i className="fa-solid fa-right-left text-xs"></i>&nbsp;
          <span className="underline">Switch to Angular</span>
        </a>
      </div>
    </div>
  );
}

// angular/src/app/components/impl-switcher/impl-switcher.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  standalone: true,
  imports: [
    CommonModule,
  ],
  selector: 'app-impl-switcher',
  templateUrl: './impl-switcher.component.html',
})
export class ImplSwitcherComponent {
  public hidden = false;

  public toggleHidden() {
    this.hidden = !this.hidden;
  }
}

<div
  class="fixed shadow-md bottom-4 right-4 flex gap-4 p-4 bg-rose-700 rounded-md text-white transition-transform"
  [ngClass]="[hidden ? 'translate-x-[83%]' : '']"
>
  <div class="flex flex-col justify-between">
    <i class="text-5xl fa-brands fa-react"></i>
    <button (click)="toggleHidden()" class="text-md text-rose-400">
      <i
        class="fa-solid"
        [ngClass]="[hidden ? 'fa-arrow-left' : 'fa-arrow-right']"
      ></i>
    </button>
  </div>
  <div class="flex flex-col items-start justify-between">
    <span class="text-rose-200"> This site was built with Angular. </span>
    <span class="text-rose-200">Need a React developer?</span>
    <a href="/react">
      <i class="fa-solid fa-right-left text-xs"></i>&nbsp;
      <span class="underline">Switch to React</span>
    </a>
  </div>
</div>
